In [1]:
import pandas as pd
data = pd.read_csv('fifa21_train.csv')

import functions # this imports a function saves as a .py file in the same directory
data

,ID,Name,Age,Nationality,Club,BP,Position,Team & Contract,Height,Weight,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
0,184383,A. Pasche,26,Switzerland,FC Lausanne-Sport,CM,CM CDM,FC Lausanne-Sport 2015 ~ 2020,"5'9""",161lbs,...,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1,64
1,188044,Alan Carvalho,30,China PR,Beijing Sinobo Guoan FC,ST,ST LW LM,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan","6'0""",159lbs,...,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2,77
2,184431,S. Giovinco,33,Italy,Al Hilal,CAM,CAM CF,Al Hilal 2019 ~ 2022,"5'4""",134lbs,...,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2,80
3,233796,J. Evans,22,Wales,Swansea City,CDM,CDM CM,Swansea City 2016 ~ 2021,"5'10""",152lbs,...,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2,59
4,234799,Y. Demoncy,23,France,US Orléans Loiret Football,CDM,CDM CM,US Orléans Loiret Football 2018 ~ 2021,"5'11""",150lbs,...,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11696,232504,B. Böðvarsson,25,Iceland,Jagiellonia Białystok,LB,LB,Jagiellonia Białystok 2018 ~ 2021,"6'1""",168lbs,...,60+2,60+2,63+2,63+2,61+2,61+2,61+2,63+2,16+2,65
11697,214680,G. Gallon,27,France,ESTAC Troyes,GK,GK,ESTAC Troyes 2019 ~ 2022,"6'1""",174lbs,...,26+2,26+2,25+2,24+2,26+2,26+2,26+2,24+2,69+2,70
11698,221489,J. Flores,22,Chile,CD Antofagasta,RM,LM CAM RM,CD Antofagasta 2019 ~ 2024,"5'6""",143lbs,...,44+2,44+2,49+2,45+2,35+2,35+2,35+2,45+2,17+2,67
11699,146717,Anderson Silva,26,Brazil,Barnsley,CM,NaN,Barnsley 2010,"6'2""",179lbs,...,68+0,68+0,66+0,64+0,60+0,60+0,60+0,64+0,25+0,68
11700,236507,T. Conechny,22,Argentina,Portland Timbers,CAM,ST CAM LM,Portland Timbers 2019 ~ 2020,"5'7""",143lbs,...,43+2,43+2,46+2,44+2,36+2,36+2,36+2,44+2,15+2,64

In [2]:
data2 = functions.clean_data(data)
data2

,BP,Age,Height,Weight,foot,Growth,Value,Attacking,Skill,Movement,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,OVA
0,CM,26,175.26,161,Right,1,525000.0,258,286,346,...,High,Medium,1,69,51,63,63,51,60,64
1,ST,30,182.88,159,Right,0,8500000.0,365,375,404,...,High,Low,2,83,75,68,82,33,71,77
2,CAM,33,162.56,134,Right,0,9000000.0,336,424,424,...,High,Medium,2,80,77,78,86,27,56,80
3,CDM,22,177.80,152,Right,13,275000.0,242,259,282,...,Medium,Medium,1,57,44,54,57,57,60,59
4,CDM,23,180.34,150,Right,8,725000.0,249,280,324,...,Low,Medium,1,66,44,60,64,60,66,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11696,LB,25,185.42,168,Left,5,625000.0,224,248,333,...,Medium,Medium,1,75,28,56,59,60,69,65
11697,GK,27,185.42,174,Right,4,1600000.0,84,96,237,...,Medium,Medium,1,72,67,66,72,40,70,70
11698,RM,22,167.64,143,Right,8,1100000.0,286,291,388,...,High,Medium,1,76,60,60,72,26,43,67
11699,CM,26,187.96,179,Right,7,0.0,254,284,198,...,Medium,Medium,3,72,63,70,72,57,66,68
11700,CAM,22,170.18,143,Left,9,700000.0,289,267,391,...,High,Low,1,79,62,56,67,24,48,64

In [4]:
y,X = functions.y_X(data2,'OVA')
display(y)
X

0        64
1        77
2        80
3        59
4        65
         ..
11696    65
11697    70
11698    67
11699    68
11700    64
Name: OVA, Length: 11701, dtype: int64

,Age,Height,Weight,Growth,Value,Attacking,Skill,Movement,Power,Mentality,...,BP_RB,BP_RM,BP_RW,BP_RWB,BP_ST,foot_Right,A/W_Low,A/W_Medium,D/W_Low,D/W_Medium
0,0.370370,0.40,0.349206,0.074074,0.005833,0.556931,0.569087,0.663818,0.556270,0.654596,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.518519,0.55,0.333333,0.037037,0.094444,0.821782,0.777518,0.829060,0.768489,0.718663,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
2,0.629630,0.15,0.134921,0.037037,0.100000,0.750000,0.892272,0.886040,0.562701,0.771588,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.222222,0.45,0.277778,0.518519,0.003056,0.517327,0.505855,0.481481,0.463023,0.562674,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,0.259259,0.50,0.261905,0.333333,0.008056,0.534653,0.555035,0.601140,0.472669,0.665738,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11696,0.333333,0.60,0.404762,0.222222,0.006944,0.472772,0.480094,0.626781,0.450161,0.587744,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
11697,0.407407,0.60,0.452381,0.185185,0.017778,0.126238,0.124122,0.353276,0.270096,0.128134,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
11698,0.222222,0.25,0.206349,0.333333,0.012222,0.626238,0.580796,0.783476,0.466238,0.518106,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
11699,0.370370,0.65,0.492063,0.296296,0.000000,0.547030,0.564403,0.242165,0.401929,0.518106,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
11700,0.222222,0.30,0.206349,0.370370,0.007778,0.633663,0.524590,0.792023,0.575563,0.526462,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0